<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.4.5</version>
        <relativePath />
    </parent>
    <groupId>com.eduai</groupId> <!-- lookup parent from repository -->
    <artifactId>eduai</artifactId><!-- lookup parent from repository -->
    <version>1.0.0</version>
    <packaging>pom</packaging>
    <name>eduai</name><!-- lookup parent from repository -->
    <url />

    <properties>
        <java.version>21</java.version>
        <spring-cloud.version>2024.0.0</spring-cloud.version>
        <graalvm.version>24.1.1</graalvm.version>
        <avro.version>1.12.0</avro.version>
        <avro-serializer.version>7.8.0</avro-serializer.version>
        <ikon.sdk.version>1.0.0</ikon.sdk.version>
        <human-capital-management.version>1.0.0</human-capital-management.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <modules>
        <module>auth-service/auth-client</module>
        <module>auth-service/auth-server</module>
        <module>mail-service/mailservice-client</module>
        <module>mail-service/mailservice-server</module>
        <module>api-gateway-service</module>
        <module>task-service</module>
    </modules>
</project>